### ISSUE TITLE
Issue with Y_c, should use Y

### ISSUE THREAD

**Issue by BenjaminRisk** [thebrisklab/ProJIVE#2]
https://github.com/thebrisklab/ProJIVE/blob/547fb2c1707358a63a94d536e06190e996c046b8/Functions_for_PJIVE.R#L956

HEY @rmurden ! I think this should be Y since the function later on uses Y. Maybe we should have a default that applies centering to Y prior to the EM function, but also allows the option to not center?

**Comment by rmurden** [comment]
Sounds good to me. I'll update it!

Raphiel J. Murden, Ph.D. (he/him/his)
Assistant Research Professor
Department of Biostatistics and Bioinformatics
Rollins School of Public Health
Emory University
Grace Crum Rollins Bldg., Room 312
Email: ***@***.******@***.***>
Phone: 404.727.0859

From: Ben Risk ***@***.***>
Sent: Friday, February 24, 2023 3:01 PM
To: thebrisklab/ProJIVE ***@***.***>
Cc: Murden, Raphiel ***@***.***>; Mention ***@***.***>
Subject: [External] [thebrisklab/ProJIVE] Issue with Y_c, should use Y (Issue #2)


https://github.com/thebrisklab/ProJIVE/blob/547fb2c1707358a63a94d536e06190e996c046b8/Functions_for_PJIVE.R#L956<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthebrisklab%2FProJIVE%2Fblob%2F547fb2c1707358a63a94d536e06190e996c046b8%2FFunctions_for_PJIVE.R%23L956&data=05%7C01%7Cr.j.murden%40emory.edu%7C4a9d446bae9248b5e60c08db16a1e79c%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638128656857285912%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VStI7A3kBA33XWQiBAFONNTTTjvgt%2BGfKWjKgJHyZhA%3D&reserved=0>

HEY @rmurden<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frmurden&data=05%7C01%7Cr.j.murden%40emory.edu%7C4a9d446bae9248b5e60c08db16a1e79c%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638128656857285912%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Yh9MnaDIBv0yoP2V%2BPeRgec5pUtcMKBWPtkEkaFAZ9s%3D&reserved=0> ! I think this should be Y since the function later on uses Y. Maybe we should have a default that applies centering to Y prior to the EM function, but also allows the option to not center?

-

**Comment by rmurden** [comment]
Hi Ben, 

I started a new branch (Y_Centering_Option) to try and ensure that I didn't screw anything up by adding the option you referenced. Things look like they're working fine. So, I think we can merge my new branch into the main one. However, if you'd like to check first, please look at the updated "PJIVE_Vignette.R" script.
